### PR TITLE
Expose namespace and short name as explicit entities

### PR DESCRIPTION
**Pull request by JoelMarcey**

### CODE REVIEW

**Comment by fredemmott** [comment]
- this is modelled on Reflection* , so it should be getNamespaceName, not getNamespace
 - should also apply to ReflectionFunction
 - tests :)

**Comment by fredemmott** [comment]
RE applying to other functions, there's a chance this could go in scannedBase, as all subclasses define getName()

**Comment by JoelMarcey** [comment]
Ahh - and namespace would just be null for those things that don't have it.

**Comment by fredemmott** [comment]
It should return an empty string for no namespace instead of null (I don't like it, but the whole emulating Reflection* thing again)

**Pull request merged**
